name: gtc-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - astropy
  - astroquery
  - astroscrappy
  - ccdproc
  - matplotlib
  - numpy
  - photutils
  - scipy
  - sep
